name: GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            .cpcache
            .shadow-cljs
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bb: latest

      - name: Build static site
        run: bb build-static

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
