name: CLJ-Kondo

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bb: latest

      - name: Cache kondo directory
        uses: actions/cache@v4
        with:
          path: ~/.clj-kondo/.cache
          key: ${{ runner.os }}-kondo
          restore-keys: ${{ runner.os }}-kondo

      - name: Run clj-kondo
        run: bb lint --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
